name: fidh_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.1.0

  # State Management
  flutter_riverpod: ^2.5.1

  # API Call
  http: ^1.2.1
  flutter_dotenv: ^5.1.0

  # Utility & Features
  flutter_dotenv: ^5.1.0
  file_picker: ^8.0.5
  image_picker: ^1.1.2
  speech_to_text: ^7.3.0
  url_launcher: ^6.2.6
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1 # <-- TAMBAHKAN BARIS INI

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env