// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzYiSW3hLE1Z1casdLhjsjeXmkVz8aEMg',
    appId: '1:262222975011:web:ffb2447690f5388056e196',
    messagingSenderId: '262222975011',
    projectId: 'roshadiproject',
    authDomain: 'roshadiproject.firebaseapp.com',
    storageBucket: 'roshadiproject.firebasestorage.app',
    measurementId: 'G-3YQVKS5SXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH1UQh-TYca1DLv_R9tPzH7Arv-7s2Law',
    appId: '1:262222975011:android:879b3edd7409854456e196',
    messagingSenderId: '262222975011',
    projectId: 'roshadiproject',
    storageBucket: 'roshadiproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlFuws0zITu9c-q9WVUnT9bLsrgZkxeyI',
    appId: '1:262222975011:ios:588d12fd4859d11e56e196',
    messagingSenderId: '262222975011',
    projectId: 'roshadiproject',
    storageBucket: 'roshadiproject.firebasestorage.app',
    iosBundleId: 'com.example.fidhAiBaru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlFuws0zITu9c-q9WVUnT9bLsrgZkxeyI',
    appId: '1:262222975011:ios:588d12fd4859d11e56e196',
    messagingSenderId: '262222975011',
    projectId: 'roshadiproject',
    storageBucket: 'roshadiproject.firebasestorage.app',
    iosBundleId: 'com.example.fidhAiBaru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzYiSW3hLE1Z1casdLhjsjeXmkVz8aEMg',
    appId: '1:262222975011:web:330b3197e1b5f69756e196',
    messagingSenderId: '262222975011',
    projectId: 'roshadiproject',
    authDomain: 'roshadiproject.firebaseapp.com',
    storageBucket: 'roshadiproject.firebasestorage.app',
    measurementId: 'G-MWYF98J9KS',
  );

}